### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ajsonnick** [mauryaratan/stag-custom-sidebars#5]
What is the css slug I should be adding to  my css file so I can customize this? I want this to look like my normal sidebar.

Thanks,
AJ

**Comment by ajsonnick** [comment]
HELLO?

**Comment by mauryaratan** [comment]
You can find the class on this line - https://github.com/mauryaratan/stag-custom-sidebars/blob/master/stag-custom-sidebars.php#L312. You can find additional details on adding custom classes on plugin's [description](https://wordpress.org/plugins/stag-custom-sidebars/) page.
